### ISSUE TITLE
Translate multiselect labels

### ISSUE THREAD

**Issue by stand579** [bentorfs/angular-bootstrap-multiselect#23]
Hello,

First of all thank you for the great directive. We've been using it successfully in our application and we're very satisfied.

However, now our application evolved to the point we need to translate it into many languages. I was looking into the source code (release version 1.1.4) and saw that labels like "Select", "Select All", "Unselect All" and "{{ N }} selected" are hard-coded in the code, so we can't translate them.

Could you please change the directive to allow us provide translations in different languages?

Thanks in advance.

**Comment by bentorfs** [comment]
Hi Stanislava,

I am not currently actively maintaining this, but you are welcome to fork
the project and/or make a pull request :-)

Cheers,

Ben

**Comment by stand579** [comment]
Thanks Ben, are you planning to release a new version soon?

**Comment by bentorfs** [comment]
I can do a grunt bump (or you can do it yourself, I made you collaborator),
but I'm not sure what the process is like to upload to NPM. It was done by
AmitMY in https://github.com/bentorfs/angular-bootstrap-multiselect/issues/9

**Comment by stand579** [comment]
The fix for this issue was added in PR #25 so I'm closing this issue.
