### ISSUE TITLE
Support asynchronous search results

### ISSUE THREAD

**Issue by bentorfs** [bentorfs/angular-bootstrap-multiselect#3]

**Comment by javierpsf** [comment]
Hi bentorfs!

firstly thank a lot for your great job.

I am reviewing this review and not whether it is related to the problem I have now. When I update the values of multiselect combo following an onChange another combo, the changes are not displayed.

you can show me an example of how to do?

I'm trying to implement an example you have in Asynchronous Datasource but don't work.

Can you help me?

Thank you very much.

javiP

**Comment by bentorfs** [comment]
This ticket is for when you want the suggested results to be dependent on a server query. It sounds like this is not the case for you and you just want to replace the options when some action triggers. In this case, just replace the options variable on the scope, and two-way binding will do the rest
