### ISSUE TITLE
Latest npm version is 1.1.2

### ISSUE THREAD

**Issue by Duskfall** [bentorfs/angular-bootstrap-multiselect#30]
Please update the npm package to latest version. It says that only available versions are 
npm ERR! Valid install targets:
npm ERR! 1.1.2, 0.0.3

**Comment by AmitMY** [comment]
Done.

**Comment by Duskfall** [comment]
Latest version breaks when installing. A dependency isn't present.
````
Error: Cannot find module '\node_modules\angular-bootstrap-multiselect\node_modules\protractor\bin\webdriver-manager'

**Comment by celina** [comment]
This issue should be reopened - the fix introduced new issues that are still unresolved.

**Comment by AmitMY** [comment]
@celina This issue regards the npm version, not any other issue
