### ISSUE TITLE
Options Can Disappear from the List Entirely

### ISSUE THREAD

**Issue by justinlinz** [bentorfs/angular-bootstrap-multiselect#38]
Some sequences can lead to items disappearing from the list of options.  The following steps will reproduce:

Click Select All
Click Select All
Click an option to deselect it
That option is now nowhere to be found.

A working example of the bug is here:
[https://jsfiddle.net/justinlinz/8dkg87bL/](https://jsfiddle.net/justinlinz/8dkg87bL/)

The issue is due to a reference of the item list being modified.  I will add a pull request to remedy this.

**Comment by bentorfs** [comment]
Good catch. Thanks!

**Comment by bentorfs** [comment]
Fixed in 1.1.7 and published to NPM

**Comment by justinlinz** [comment]
Thanks for the quick merge!
