### ISSUE TITLE
Display a prepopulated values`

### ISSUE THREAD

**Issue by smfinvest** [bentorfs/angular-bootstrap-multiselect#51]
I have successfully pre-populated the multiselect using the id-prop. When I click on the dropdown it DOES show my pre-selected value(s). But it does not show up in the initial view of the dropdown, neither the selected item name nor the '2 Selected' value. How do I trigger that, or can it be added to the code.

**Comment by smfinvest** [comment]
![image](https://user-images.githubusercontent.com/10522764/29984833-d5fd5d80-8f21-11e7-9d5a-069060c8208c.png)

Here you see that the values are set but the display is still as if none are selected.
![image](https://user-images.githubusercontent.com/10522764/29984866-07738d1c-8f22-11e7-837b-d934f33a2de1.png)

**Comment by nicomigliaccio** [comment]
How did you solve it?

**Comment by nlaycock** [comment]
I'd also like to know how to solve this if it is at all possible...

**Comment by anujsaxna** [comment]
Do anyone got the solution for this??
