### ISSUE TITLE
Translation to: pt-br

### ISSUE THREAD

**Issue by glaucia86** [bentorfs/angular-bootstrap-multiselect#53]
Hi Ben. How are you?

I would like to know how can I translate this plugin to my language: pt-br. Once I am using your excelent plugin for my project.

Kind Regards,

Glaucia Lemos

**Comment by bentorfs** [comment]
Hi,

There is currently no support for i8n, apart from changing the placeholder text (the word "select") using the `placeholder` attribute.

Feel free to make a PR.

Cheers,

Ben

**Comment by glaucia86** [comment]
Thanks bro!



I will test here... if everything be okay... I'll do the Pull request as well!



Thanks a lot,


Glaucia Lemos
+55 21 99152-0972
Microsoft MVP - Visual Studio and Development Technologies


[1504014687719_MVP_Logo_Horizontal_Secondary_Blue286_CMYK_72ppi.png]

________________________________
De: Ben Torfs <notifications@github.com>
Enviado: terça-feira, 5 de setembro de 2017 17:15:19
Para: bentorfs/angular-bootstrap-multiselect
Cc: Glaucia Lemos; Author
Assunto: Re: [bentorfs/angular-bootstrap-multiselect] Translation to: pt-br (#53)


Hi,

There is currently no support for i8n, apart from changing the placeholder text (the word "select") using the placeholder attribute.

Feel free to make a PR.

Cheers,

Ben

**Comment by vqanguyen** [comment]
Hi bentorfs, how to translate words "Select", "Select All", "Unselect All" for multi languages support ??? Thanks for your reply.

**Comment by vqanguyen** [comment]
i've solution, try using _**labels**_ attribute

**Comment by bentorfs** [comment]
@vqanguyen you are right. Somebody contributed this feature a while ago. I added documentation here: https://bentorfs.github.io/angular-bootstrap-multiselect/#example-labels
