### ISSUE TITLE
options mistake

### ISSUE THREAD

**Issue by rifer** [bentorfs/angular-bootstrap-multiselect#8]
Hi,

great lib, thanks.

Iḿ having some mistakes when I use something like this:

<multiselect ng-model="tipo.codigoEstado" options="item.cod as item.valor for item in tipo.estados" show-select-all="true" show-unselect-all="true"></multiselect>

Any idea??

Thanks in advance

**Comment by rifer** [comment]
Something like this, sorry:

<multiselect ng-model="tipo.codigoEstado" options="item.cod as item.valor for item in tipo.estados" show-select-all="true" show-unselect-all="true"></multiselect>

**Comment by rifer** [comment]
```
<multiselect ng-model="tipo.codigoEstado" options="item.cod as item.valor for item in tipo.estados" show-select-all="true" show-unselect-all="true"></multiselect>

```

**Comment by bentorfs** [comment]
Hi Rifer,

You cannot use an expression like that for 'options'. You need to just specify a list of objects. You can use display-prop to indicate which field on the objects should be used as display name

**Comment by rifer** [comment]
Thanks a lot, solved ;-)

By the way, how to show the selected data if I como from a get with some data?

Sorry for all this inconveniences

**Comment by bentorfs** [comment]
You have to set a $q promise instead of a list as the options value. There
is an example on the documentation page, on the bottom

**Comment by rifer** [comment]
Thank you so much.

I'm closing the issue and from now I'll read always the whole documentation.
