### ISSUE TITLE
install with NPM

### ISSUE THREAD

**Issue by edouard-lopez** [bentorfs/angular-bootstrap-multiselect#9]
Please create a NPM package so it can be install using

```
npm install angular-bootstrap-multiselect --save
```

See  [npm-create](https://www.npmjs.com/package/npm-create) or [create npm package](https://duckduckgo.com/?q=create+npm+package&t=ffab).

**Comment by AmitMY** [comment]
Not an official source, but here you go:
https://www.npmjs.com/package/angular-bootstrap-multiselect

**Comment by bentorfs** [comment]
Thanks Amit :-)

**Comment by AmitMY** [comment]
No problem
You can close if you want

**Comment by stand579** [comment]
Hi @AmitMY I tried to update the npm package to the latest version to fix #30 but I couldn't update it as you're the npm package owner. Could you please update it to the latest version?

**Comment by AmitMY** [comment]
Done.

@bentorfs Can I add you to the list of "collaborators" on npm, such that you will be able to publish? (what is your npm username?)

Such a simple process:
- `git clone https://github.com/bentorfs/angular-bootstrap-multiselect.git`
- `cd angular-bootstrap-multiselect/`
- `npm publish`

**Comment by bentorfs** [comment]
My username is 'bentorfs' (In fact I only made it just for this purpose).

I suggest that you add Stanislava as collaborator as well. He's taking care
of business here lately :-)

Cheers,

Ben

**Comment by AmitMY** [comment]
You were both added as collaborators
Great to hear that this repo is not being neglected.
